#Ejericio 1
print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)
print("Jose Damian Mendez Tinoco")
print("Mendez Tinoco")
print("Mexico")
print("I am enjoying 30 days of python")